### ISSUE TITLE
Tmp file problem in runtests

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqBayes.jl#12] opened 2017-09-02 14:49 UTC
In running:
bayesian_result = bayesian_inference(prob1,t,data,priors;num_samples=100,num_warmup=100)
theta1 = bayesian_result.chain_results[:,["theta.1"],:]
@test mean(theta1.value[:,:,1]) ≈ 1.5 atol=1e-1

It produces
chdir : no such file or directory (ENOENT)

Stacktrace:
 [1] uv_error at .\libuv.jl:68 [inlined]
 [2] cd(::String) at .\file.jl:50
 [3] #stan#4(::Type{T} where T, ::Bool, ::Bool, ::String, ::Function, ::Stan.Stanmodel, ::Array{Dict{String,Any},1}, ::String) at C:\Users\Denis\.julia\v0.6\Stan\src\main\stancode.jl:74
 [4] (::Stan.#kw##stan)(::Array{Any,1}, ::Stan.#stan, ::Stan.Stanmodel, ::Array{Dict{String,Any},1}, ::String) at .\<missing>:0 (repeats 2 times)
 [5] #bayesian_inference#1(::Symbol, ::Int64, ::Int64, ::Float64, ::Float64, ::Int64, ::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LotkaVolterraTest1,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::Array{Float64,1}, ::Array{Float64,2}, ::Array{Distributions.Normal{Float64},1}) at C:\Users\Denis\.julia\v0.6\DiffEqBayes\src\bayesian_inference.jl:87
 [6] (::DiffEqBayes.#kw##bayesian_inference)(::Array{Any,1}, ::DiffEqBayes.#bayesian_inference, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LotkaVolterraTest1,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::Array{Float64,1}, ::Array{Float64,2}, ::Array{Distributions.Normal{Float64},1}) at .\<missing>:0
 [7] include_string(::String, ::String) at .\loading.jl:515

Also could you extend the test to two parameters so as to document the syntax for "priors" and "mean"

**Comment by ChrisRackauckas** [comment] 2017-09-02 16:29
`mean` is just from Julia Base. `priors` needs more functionality because being documented. Right now it just works for `Normal`.

That error is because you never installed CmdStan. See Stan.jl.

**Comment by ChrisRackauckas** [comment] 2018-01-04 10:08
This is basically just a duplicate of https://github.com/JuliaDiffEq/DiffEqBayes.jl/issues/13 . We need docs, but we'll make them when the library is ready. It's not ready yet.

**Closed by ChrisRackauckas** 2018-01-04 10:08 UTC
